#!/bin/bash
# Usage: $0 <username> <password>

# Check paramaters
if [ "$1" == "" ] ; then
    echo "Usage: $0 <username> <password>"
    exit 1
fi
if [ "$2" == "" ] ; then
    echo "Usage: $0 <username> <password>"
    exit 1
fi
if [ "$3" != "" ] ; then
    echo "Too many parameters!"
    echo "Usage: $0 <username> <password>"
    exit 1
fi

echo -e "$2\n$2" |pdbedit -t -a -u $1
