#!/bin/bash
# Usage: $0 <username>

# Check paramaters
if [ "$1" == "" ] ; then
    echo "Usage: $0 <username>"
    exit 1
fi
if [ "$2" != "" ] ; then
    echo "Too many parameters!"
    echo "Usage: $0 <username>"
    exit 1
fi

#add samba information
echo "$0: Add samba machine:"
pdbedit -a -m $1

exit 0
